name: Deploy

on:
  push:
    branches: [main] # TODO: On each push in main branch

jobs:
  deploy:
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate sourc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build static page
        run: bundle exec jekill build

      # - name: Upload Artifacts
      #   uses: actions/upload-pages-artifact
      #   with:
      #     path: _site/

      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v1
